
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <stdio.h>
#include <stdlib.h>
#include <jni.h>
#include <android/log.h>

#ifndef _FILE_UTIL_
#define _FILE_UTIL_

/*
 * Class:     com_example_nativefileio_FileSave
 * Method:    save
 * Signature: ()V
 */
#ifdef __cplusplus
extern "C" {
#endif
void getExternalRootDir (JNIEnv * env, jobject obj, char* rootDir);
#ifdef __cplusplus
}
#endif

#endif
