/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_detector_jni_LaneDetectNativeInterface */

#ifndef _Included_com_baidu_detector_jni_LaneDetectNativeInterface
#define _Included_com_baidu_detector_jni_LaneDetectNativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_detector_jni_LaneDetectNativeInterface
 * Method:    nativeGetLane
 * Signature: (JLjava/util/ArrayList;Ljava/util/ArrayList;Ljava/util/ArrayList;)V
 */
JNIEXPORT void JNICALL Java_com_baidu_detector_jni_LaneDetectNativeInterface_nativeGetLane
  (JNIEnv *, jclass, jlong, jobject, jobject, jobject);

/*
 * Class:     com_baidu_detector_jni_LaneDetectNativeInterface
 * Method:    nativeSaveAdjustedPoints
 * Signature: (FFFFFFFFII)V
 */
JNIEXPORT void JNICALL Java_com_baidu_detector_jni_LaneDetectNativeInterface_nativeSaveAdjustedPoints
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
