/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_trafficplaterecon_TrafficplateRecon */

#ifndef _Included_com_baidu_trafficplaterecon_TrafficplateRecon
#define _Included_com_baidu_trafficplaterecon_TrafficplateRecon
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_trafficplaterecon_TrafficplateRecon
 * Method:    nativeCreateObject
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_baidu_trafficplaterecon_TrafficplateRecon_nativeCreateObject
  (JNIEnv *, jclass);

/*
 * Class:     com_baidu_trafficplaterecon_TrafficplateRecon
 * Method:    nativeDestroyObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_baidu_trafficplaterecon_TrafficplateRecon_nativeDestroyObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_baidu_trafficplaterecon_TrafficplateRecon
 * Method:    nativeDetect
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_baidu_trafficplaterecon_TrafficplateRecon_nativeDetect
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
