/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_trafficplatedetect_TrafficPlateDetect */

#ifndef _Included_com_baidu_trafficplatedetect_TrafficPlateDetect
#define _Included_com_baidu_trafficplatedetect_TrafficPlateDetect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_trafficplatedetect_TrafficPlateDetect
 * Method:    nativeCreateObject
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_baidu_trafficplatedetect_TrafficPlateDetect_nativeCreateObject
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_baidu_trafficplatedetect_TrafficPlateDetect
 * Method:    nativeDetect
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_baidu_trafficplatedetect_TrafficPlateDetect_nativeDetect
  (JNIEnv *, jclass, jlong, jlong, jlong, jstring);

/*
 * Class:     com_baidu_trafficplatedetect_TrafficPlateDetect
 * Method:    nativeDestroyObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_baidu_trafficplatedetect_TrafficPlateDetect_nativeDestroyObject
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
