/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_trafficsignrecon_TrafficsignRecon */

#ifndef _Included_com_baidu_trafficsignrecon_TrafficsignRecon
#define _Included_com_baidu_trafficsignrecon_TrafficsignRecon
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_baidu_trafficsignrecon_TrafficsignRecon
 * Method:    nativeCreateObject
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_baidu_trafficsignrecon_TrafficsignRecon_nativeCreateObject
  (JNIEnv *, jclass);

/*
 * Class:     com_baidu_trafficsignrecon_TrafficsignRecon
 * Method:    nativeDestroyObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_baidu_trafficsignrecon_TrafficsignRecon_nativeDestroyObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_baidu_trafficsignrecon_TrafficsignRecon
 * Method:    nativeDetect
 * Signature: (JJJ)V
 */
JNIEXPORT jlong JNICALL Java_com_baidu_trafficsignrecon_TrafficsignRecon_nativeDetect
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
